pyteslanguage: python
python:
  - '3.6'
  - '3.7'
install:
  - 'pip install pipenv'
  - 'pipenv install'
script: 'python -m pytest'
# --cov=pyblizzard tests --cov-report=xml'
# after_success:
#  - 'python-codacy-coverage -r coverage.xml'